
version: "3.8"
services:
    dev:
        build:
            context: .
            dockerfile: ./Dockerfile
            target: dev
        tty: true
        stdin_open: true
        volumes:
            - .:/code
            - poetry:/home/docker/.cache

volumes:
    poetry:
